version: '3.1'

services:
        dbos:
                image: mysql:5.7
                volumes:
                        - sql_volume_new1:/var/lib/mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: 1234
                        MYSQL_USER: akr
                        MYSQL_PASSWORD: 1234
                        MYSQL_DATABASE: mydb
        drupalos:
                image: drupal:8-apache
                ports:
                       - 8080:80
                restart: always
                volumes:
                       - drupal-modules:/var/www/html/modules
                       - drupal-profiles:/var/www/html/profiles
                       - drupal-sites:/var/www/html/sites
                       - drupal-themes:/var/www/html/themes
                depends_on:
                       - dbos
volumes:
        drupal-modules:
        drupal-profiles:
        drupal-sites:
        drupal-themes:
        sql_volume_new1: